# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.0.x'
    - name: Restore dependencies
      run: dotnet restore src/PingmanTools.AspNet.EncryptWeMust.sln
    - name: Build
      run: dotnet build --no-restore src/PingmanTools.AspNet.EncryptWeMust.sln --configuration release
    # - uses: actions/setup-dotnet@v4
      # with:
        # dotnet-version: 3.1.x
    # - name: Publish the package to nuget.org
      # env:
        # NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      # run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json