# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.0.x'
    - name: Restore dependencies
      run: dotnet restore src/PingmanTools.AspNet.EncryptWeMust.sln
    - name: Build
      run: dotnet build --no-restore src/PingmanTools.AspNet.EncryptWeMust.sln --configuration release
    # - uses: actions/setup-dotnet@v4
      # with:
        # dotnet-version: 3.1.x
    - name: Pack
      run: dotnet pack src/PingmanTools.AspNet.EncryptWeMust/PingmanTools.AspNet.EncryptWeMust.csproj --configuration Release /p:Version=1.0.1 --no-build --output .
    - name: Publish the package to nuget.org
      env:
        nuget_auth_token: ${{ secrets.nuget_token }}
      run: dotnet nuget push PingmanTools.AspNet.EncryptWeMust.1.0.1.nupkg -k $nuget_auth_token -s https://api.nuget.org/v3/index.json
